Added Roadmaps.
Saherpathan/GenUp_Nexus pull request #43
Opened 2024-04-06 19:20 UTC by abhishek-yeole

2024-04-06 22:24 UTC, Siddhant-Patil0203 requested changes
@abhishek-yeole 
Pls. Let me know, if the server hosted on hugging face not synced with the github code, 
because the server is returning previous server version responses and not, the updated one

2024-04-06 22:24 UTC, Siddhant-Patil0203 commented on client/src/components/User/mindmaps/Mindmaps.jsx
@abhishek-yeole 
The new style to Mindamps input is not looking good, Pls. revert it to the earlier version, as it was also responsive.

2024-04-06 22:24 UTC, Siddhant-Patil0203 commented on client/src/index.css
> +
@abhishek-yeole 
Give the custom scrollbar class, as we don't want customize scrollbar for mobile screen 
![image](https://github.com/Saherpathan/GenUp_Nexus/assets/77800620/3458846b-2cca-4bab-8b3f-939a6e957b7d)
and use this class in the component or the page where you want to use custom scroll, like in CustomNode.jsx page

2024-04-06 22:24 UTC, Siddhant-Patil0203 commented on client/src/components/User/mindmaps/MindmapOpener.jsx
@abhishek-yeole 
Minimap is not updating its style with respect to the website theme button, it requires a reload, 
Pls. use `useEffect` to update it realtime. 
Or do let me know if it is because of reactflow library or its canvas render

2024-04-06 22:24 UTC, Siddhant-Patil0203 commented on client/src/components/User/mindmaps/Mindmaps.jsx
@abhishek-yeole 
Same Minimap Issue as addressed in MindmapOnener.jsx

2024-04-06 22:26 UTC, Siddhant-Patil0203 commented on client/src/index.css
> +
and remove the class in the mobile screen

2024-04-06 22:37 UTC, Siddhant-Patil0203 commented on client/src/index.css
> +
Or do one thing just add @media for mobile device and remove styling in the scrollbar

2024-04-06 23:16 UTC, Saherpathan approved these changes

2024-04-20 03:41 UTC, Siddhant-Patil0203 approved these changes

2024-04-20 03:42 UTC, merged